version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: gonotes-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: gonotes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gonotes-net

networks:
  gonotes-net:
    driver: bridge

volumes:
  pgdata:
